// require('./test/anime')
// require('./test/apiwant')
// require('./test/tiktok')
// require('./test/wantnsfwv2')
// require('./test/wantwaifux')
// require('./test/wantwaifuxsfw')
// require('./test/wanthub')
// require('./test/wantsafesearch')